import Image from "next/image";
import AISearch from "./components/AISearch";
import SidebarToggle from "./components/SidebarToggle";
import HeaderActions from "./components/HeaderActions";
import HorizontalCarousel from "./components/HorizontalCarousel";
import HeroCarousel from "./components/HeroCarousel";

type I="home"|"building"|"map"|"bag"|"tools"|"briefcase"|"users"|"calendar"|"crown"|"heart"|"bell"|"profile"|"settings"|"wallet"|"search"|"sparkles"|"diamond"|"arrow"|"play"|"location"|"refresh"|"instagram";
const paths:Record<I,React.ReactNode>={
home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></>,building:<><path d="M4 21V5l8-3v19M12 8h8v13M8 6v2m0 3v2m0 3v2m8-6v2m0 3v2M2 21h20"/></>,bag:<><path d="M5 8h14l1 13H4L5 8Z"/><path d="M9 8V5a3 3 0 0 1 6 0v3"/></>,tools:<><path d="m14 7 3-3 3 3-3 3M4 20l9-9M5 4l4 4-2 2-4-4 2-2Zm10 10 5 5-2 2-5-5"/></>,briefcase:<><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V4h6v3M3 12h18M10 12v2h4v-2"/></>,users:<><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c0-4 2-6 6-6s6 2 6 6M15 15c3.5 0 5 1.5 5 4.5"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4m8-4v4M3 10h18m9-13 1 2 2 .3-1.5 1.5.4 2.2-1.9-1-1.9 1 .4-2.2L9 15.3l2-.3 1-2Z"/></>,crown:<><path d="m3 7 4 4 5-7 5 7 4-4-2 12H5L3 7ZM5 19h14"/></>,heart:<path d="M20.8 4.6a5.4 5.4 0 0 0-7.7 0L12 5.7l-1.1-1.1a5.4 5.4 0 0 0-7.7 7.7L12 21l8.8-8.7a5.4 5.4 0 0 0 0-7.7Z"/>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,profile:<><circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3-7 8-7s8 2 8 7"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 .4 2l-2.8 2.8a2 2 0 0 0-2-.4A2 2 0 0 0 13 21H9a2 2 0 0 0-1.6-1.6 2 2 0 0 0-2 .4L2.6 17a2 2 0 0 0 .4-2A2 2 0 0 0 1 13V9a2 2 0 0 0 2-1.6 2 2 0 0 0-.4-2L5.4 2.6a2 2 0 0 0 2 .4A2 2 0 0 0 9 1h4a2 2 0 0 0 1.6 2 2 2 0 0 0 2-.4l2.8 2.8a2 2 0 0 0-.4 2A2 2 0 0 0 21 9v4a2 2 0 0 0-2 2Z"/></>,wallet:<><path d="M3 7h16a2 2 0 0 1 2 2v10H5a2 2 0 0 1-2-2V7ZM3 7V5a2 2 0 0 1 2-2h12v4M16 12h5v4h-5a2 2 0 0 1 0-4Z"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,sparkles:<><path d="m12 3 1.4 3.6L17 8l-3.6 1.4L12 13l-1.4-3.6L7 8l3.6-1.4L12 3ZM5 14l.8 2.2L8 17l-2.2.8L5 20l-.8-2.2L2 17l2.2-.8L5 14Z"/></>,diamond:<><path d="M3 7h18l-9 14L3 7Zm4 0 5 14 5-14M3 7l4-4h10l4 4"/></>,arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,play:<path d="m8 5 11 7-11 7V5Z"/>,location:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,refresh:<><path d="M20 7v5h-5M4 17v-5h5M6 8a7 7 0 0 1 12-2l2 6m-2 4a7 7 0 0 1-12 2l-2-6"/></>,instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor"/></>};
export function Icon({name,size=21}:{name:I,size?:number}){return <svg aria-hidden width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}

export const main:[I,string,string][]=[["home","მთავარი","/"],["building","უძრავი ქონება","/real-estate"],["location","რუკა","/map"],["bag","მარკეტპლეისი","/marketplace"],["tools","სერვისები","/services"],["briefcase","ბიზნესი","/business"],["users","საზოგადოება","/community"],["calendar","ღონისძიებები","#"],["crown","JIBU Black","#"]];
const user:[I,string,string][]=[["heart","ქალთა სივრცე","#"],["heart","რჩეულები","#"],["bell","შეტყობინებები","#"],["profile","ჩემი პროფილი","/profile"],["settings","პარამეტრები","#"]];
const cats:[I,string][]=[["building","უძრავი ქონება"],["bag","მარკეტპლეისი"],["tools","სერვისები"],["briefcase","ბიზნესი"],["calendar","ღონისძიებები"],["users","საზოგადოება"],["diamond","შეთავაზებები"]];
const props=[{slug:"city-view-residence",image:"property-1",tag:"TURBO",place:"თბილისი, საბურთალო",title:"City View Residence",price:"345,000 ₾",area:"75 მ²"},{slug:"design-apartment",image:"property-2",tag:"TURBO",place:"თბილისი, ვაკე",title:"Design Apartment",price:"420,000 ₾",area:"112 მ²"}];

export function Sidebar({active="home"}:{active?:"home"|"real-estate"|"map"|"marketplace"|"services"|"business"|"community"}){return <aside className="sidebar"><a className="brand" href="/"><Image unoptimized src="/assets/logo-transparent.png" alt="JIBU" width={650} height={300} priority/></a><nav>{main.map(([i,l,href])=><a className={(active==="home"&&i==="home")||(active==="real-estate"&&i==="building")||(active==="map"&&i==="location")||(active==="marketplace"&&i==="bag")||(active==="services"&&i==="tools")||(active==="business"&&i==="briefcase")||(active==="community"&&i==="users")?"active":""} href={href} key={l}><Icon name={i}/><span>{l}</span></a>)}<div className="nav-separator"/>{user.map(([i,l,href])=><a href={href} key={l}><Icon name={i}/><span>{l}</span></a>)}</nav><section className="ai-agent"><div className="agent-title"><strong>JIBU AI</strong><span>BETA</span></div><p>შენი AI ასისტენტი.</p><button><Icon name="sparkles" size={18}/> დაწყება</button></section></aside>}
export function Header(){return <header className="topbar"><details className="mobile-menu"><summary><span/><span/><span/></summary><div>{main.map(([i,l,href])=><a href={href} key={l}><Icon name={i}/>{l}</a>)}{user.map(([i,l,href])=><a href={href} key={l}><Icon name={i}/>{l}</a>)}</div></details><div className="mobile-logo"><Image unoptimized src="/assets/logo-transparent.png" alt="JIBU" width={130} height={60}/></div><SidebarToggle/><AISearch/><HeaderActions/></header>}
function Hero(){return <HeroCarousel>
  <div className="home-hero-content"><Image unoptimized src="/assets/concept/hero-ecosystem.webp" alt="JIBU — სხვადასხვა შესაძლებლობა ერთ ციფრულ სივრცეში" fill priority sizes="(max-width:1040px) 100vw,65vw"/><div className="hero-shade"/><div className="hero-copy"><span className="hero-kicker"><Icon name="sparkles" size={15}/> JIBU — შენი ყოველდღიური სივრცე</span><h1>ყველაფერი მნიშვნელოვანი<br/><em>ერთ სივრცეში.</em></h1><p>JIBU აერთიანებს ყოველდღიურ საჭიროებებს — უძრავ ქონებას, ნივთებსა და სერვისებს. დაიწყე სასურველი კატეგორიით.</p><div><a className="primary" href="#home-categories">დაიწყე აღმოჩენა <Icon name="arrow" size={18}/></a><a className="ghost" href="/map"><Icon name="location" size={17}/> გახსენი რუკა</a></div></div></div>
  <div className="home-hero-content"><Image unoptimized src="/assets/concept/hero-discover.webp" alt="ლოკაციების აღმოჩენა — JIBU" fill sizes="(max-width:1040px) 100vw,65vw"/><div className="hero-shade"/><div className="hero-copy"><span className="hero-kicker">JIBU REAL ESTATE</span><h1>იპოვე ბინა<br/><em>პირდაპირ რუკაზე.</em></h1><p>აირჩიე იყიდება ან ქირავდება, მიუახლოვდი სასურველ უბანს და დააჭირე პინს განცხადების სანახავად.</p><div><a className="primary" href="/map">რუკის გახსნა <Icon name="arrow" size={18}/></a></div></div></div>
  <div className="home-hero-content"><Image unoptimized src="/assets/concept/marketplace-lifestyle.webp" alt="ნივთები სახლისა და ყოველდღიურობისთვის" fill sizes="(max-width:1040px) 100vw,65vw"/><div className="hero-shade"/><div className="hero-copy"><span className="hero-kicker">JIBU MARKETPLACE</span><h1>იპოვე ნივთები<br/><em>ერთი კალათით.</em></h1><p>შერჩეული ნივთები სახლისთვის, სტილისთვის და ყოველდღიური ცხოვრებისთვის.</p><div><a className="primary" href="/marketplace">მარკეტპლეისის გახსნა <Icon name="arrow" size={18}/></a></div></div></div>
  <div className="home-hero-content"><Image unoptimized src="/assets/concept/hero-black.webp" alt="JIBU Black-ის პრემიუმ წევრობის ბარათი" fill sizes="(max-width:1040px) 100vw,65vw"/><div className="hero-shade"/><div className="hero-copy"><span className="hero-kicker"><Icon name="crown" size={16}/> JIBU BLACK</span><h1>მეტი შესაძლებლობა.<br/><em>გამორჩეული წევრობა.</em></h1><p>JIBU Black-ისთვის ვამზადებთ პარტნიორების სპეციალურ შეთავაზებებსა და წევრობის პრივილეგიებს. დეტალებს მალე გაგიზიარებთ.</p><div><a className="primary" href="#jibu-black">JIBU Black <Icon name="arrow" size={18}/></a></div></div></div>
</HeroCarousel>}
function Property({p}:{p:typeof props[number]}){return <article className="property-card"><a className="property-card-link" href={`/real-estate/property/${p.slug}`}><div className="property-photo"><Image unoptimized src={`/assets/concept/${p.image}.webp`} alt={p.title} fill sizes="(max-width:760px) 78vw, 22vw"/><span>{p.tag}</span><i aria-hidden><Icon name="heart" size={17}/></i></div><div className="property-body"><small><Icon name="location" size={13}/>{p.place}</small><h3>{p.title}</h3><div><strong>{p.price}</strong><span>{p.area}</span></div></div></a></article>}
function Rail(){return <aside className="right-rail"><section id="jibu-black" className="black-card"><div><span className="premium-label"><Icon name="crown" size={16}/> პრემიუმ წევრობა</span><h2>JIBU Black</h2><p>განსაკუთრებული შეთავაზებები და პრივილეგიები ერთ წევრობაში.</p><span className="black-coming">მალე JIBU-ზე</span></div><Image className="black-card-art" unoptimized src="/assets/concept/hero-black.webp" alt="JIBU Black წევრობის ბარათი" fill sizes="(max-width:1040px) 100vw,350px"/></section><section className="women-card"><div><span>JIBU WOMEN</span><h2>შენი სივრცე</h2><p>სილამაზე, სტილი და ახალი შთაგონება ყოველდღე.</p><button>აღმოაჩინე <Icon name="arrow" size={15}/></button></div><Image unoptimized src="/assets/concept/women-style-v2.webp" alt="ქალთა სივრცე — სილამაზე და სტილი" fill sizes="(max-width:1040px) 100vw,350px"/></section><section className="wallet-card"><div><small>JIBU საფულე</small><strong>0.00 ₾</strong><span>ხელმისაწვდომი ბალანსი</span></div><div className="wallet-icon"><Icon name="wallet" size={34}/></div><Icon name="arrow" size={18}/></section><List title="სწრაფი მოქმედებები" items={[["home","განცხადების დამატება"],["refresh","განახლება"],["heart","რჩეულები"],["bell","შეტყობინებები"]]}/></aside>}
function List({title,items}:{title:string,items:[I,string][]}){return <section className="rail-list"><h3>{title}</h3>{items.map(([i,l])=><a href="#" key={l}><Icon name={i}/>{l}<Icon name="arrow"/></a>)}</section>}
export default function Home(){return <div className="app-shell"><Sidebar/><div className="page"><Header/><main className="content home-content"><div className="primary-column"><Hero/><section id="home-categories" className="category-grid home-categories" aria-label="JIBU კატეგორიები">{cats.map(([i,l])=><a className={`category-tile category-${i}`} href={i==="building"?"/real-estate":i==="bag"?"#home-market":"#home-categories"} key={l}><span className="category-icon"><Icon name={i} size={24}/></span><span className="category-name">{l}</span></a>)}</section><section><div className="section-heading"><div><h2>უძრავი ქონება</h2></div><a href="/real-estate">ყველას ნახვა <Icon name="arrow" size={15}/></a></div><HorizontalCarousel>{props.map(p=><Property p={p} key={p.title}/>)}</HorizontalCarousel></section><section id="home-market" className="market-section"><div className="market-copy"><span>მარკეტპლეისი</span><h2>შენი სტილი.<br/>შენი არჩევანი.</h2><p>აღმოაჩინე შერჩეული ნივთები სახლისთვის, ტექნოლოგიებისთვის და ყოველდღიური ცხოვრებისთვის.</p><button>მარკეტპლეისის გახსნა <Icon name="arrow" size={17}/></button></div><Image unoptimized src="/assets/concept/marketplace-lifestyle.webp" alt="მარკეტპლეისის პროდუქტები" fill sizes="(max-width:760px) 100vw,60vw"/></section></div><Rail/></main></div></div>}
