"use client";
import {useEffect,useRef,useState} from "react";
import {brokerAccessExpiry,useAuth,requireUser,loginPath,navigateApp} from "../auth-client";

type Row={id:number;title:string;deal:"იყიდება"|"ქირავდება";area:string;phone:string;location:string;price:string;share:string;floor:string;note:string};
function ExcelLogo(){return <span className="excel-logo" aria-hidden><b>X</b><i><span/><span/><span/></i></span>}
function DownloadIcon(){return <svg aria-hidden width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M12 3v12m-4-4 4 4 4-4M4 20h16"/></svg>}
export default function BrokerSheet(){
 const {user}=useAuth();
 const[open,setOpen]=useState(false);const[gate,setGate]=useState(false);const[subscribed,setSubscribed]=useState(false);const subRef=useRef(false);const[rows,setRows]=useState<Row[]>([]);const[rowOwner,setRowOwner]=useState("");const[currency,setCurrency]=useState<"GEL"|"USD">("GEL");
 useEffect(()=>{
   setOpen(false);setGate(false);setRows([]);setRowOwner("");
   let expiryTimer:ReturnType<typeof setTimeout>|undefined;
   const sync=()=>{if(expiryTimer)clearTimeout(expiryTimer);const expires=user?brokerAccessExpiry(user.id):0;const active=!!user&&expires>Date.now();setSubscribed(active);subRef.current=active;if(active)expiryTimer=setTimeout(sync,Math.min(expires-Date.now()+50,2147483647));};sync();
   if(user){try{setRows(JSON.parse(localStorage.getItem(`jibu-broker-sheet:${user.id}`)||"[]"))}catch{}setRowOwner(user.id);}
   const onAdd=async(e:Event)=>{const verified=await requireUser();if(!verified||verified.id!==user?.id)return;if(!subRef.current){setGate(true);return}const p=(e as CustomEvent).detail;setRows(v=>[...v,{id:Date.now(),title:p.title,deal:p.deal,area:p.area,phone:p.phone,location:p.location,price:p.price,share:"",floor:p.floor,note:""}]);setOpen(true)};
   window.addEventListener("jibu:add-property",onAdd);window.addEventListener("jibu:subscription",sync);
   return()=>{if(expiryTimer)clearTimeout(expiryTimer);window.removeEventListener("jibu:add-property",onAdd);window.removeEventListener("jibu:subscription",sync)};
 },[user?.id]);
 useEffect(()=>{if(user&&rowOwner===user.id)localStorage.setItem(`jibu-broker-sheet:${user.id}`,JSON.stringify(rows))},[rows,rowOwner,user?.id]);
 const update=(id:number,key:keyof Row,value:string)=>setRows(v=>v.map(r=>r.id===id?{...r,[key]:value}:r));
 const addRow=()=>setRows(v=>[...v,{id:Date.now(),title:"",deal:"იყიდება",area:"",phone:"",location:"",price:"",share:"",floor:"",note:""}]);
 const convertedPrice=(value:string)=>{const amount=Number(value.replace(/[^\d.]/g,""));if(!amount)return value;return currency==="USD"?`$${Math.round(amount/2.6125).toLocaleString("en-US")}`:`${Math.round(amount).toLocaleString("en-US")} ₾`};
 const download=()=>{const head=["გარიგება","ობიექტი","მდებარეობა","კვადრატულობა","სართული",`ფასი (${currency})`,"საკონტაქტო ნომერი","ბროკერის წილი","შენიშვნა"];const csv="\uFEFF"+[head,...rows.map(r=>[r.deal,r.title,r.location,r.area,r.floor,convertedPrice(r.price),r.phone,r.share,r.note])].map(a=>a.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`JIBU-properties-${currency}.csv`;a.click();URL.revokeObjectURL(a.href)};
 const launch=async()=>{if(!user){navigateApp(loginPath("/real-estate"));return}if(!await requireUser())return;subscribed?setOpen(true):setGate(true)};
 if(!user||!subscribed)return null;
 return <><button className={`excel-fab ${!subscribed?"locked":""}`} onClick={launch} aria-label="VIP Broker ცხრილის გახსნა"><ExcelLogo/><span><small>{subscribed?"VIP BROKER":"VIP BROKER · LOCKED"}</small>ქონების ცხრილი</span></button>{gate&&<div className="broker-gate-backdrop" onMouseDown={()=>setGate(false)}><section className="broker-gate" onMouseDown={e=>e.stopPropagation()}><button className="gate-close" onClick={()=>setGate(false)}>×</button><span className="gate-crown">VIP</span><small>JIBU PROFESSIONAL</small><h2>VIP Broker გამოწერა</h2><p>ქონების ცხრილი და პროფესიონალური ბროკერის ინსტრუმენტები ხელმისაწვდომია მხოლოდ აქტიური გამოწერით.</p><div className="gate-benefits"><span>პირადი Excel სამუშაო სივრცე</span><span>ქონების ერთი დაჭერით დამატება</span><span>პორტფელის ექსპორტი და ანალიტიკა</span><span>პროფესიონალური ბროკერის სტატუსი</span></div><a href="/real-estate/vip-broker">უპირატესობების ნახვა და შეძენა</a></section></div>}{open&&<section className="excel-panel" aria-label="უძრავი ქონების ჩაშენებული ცხრილი"><header><div><ExcelLogo/><span><span className="excel-vip">JIBU PRIVATE TOOLS</span><strong>VIP Broker Excel</strong><small>{rows.length} ჩანაწერი · პირადი ქონების ბაზა</small></span></div><div><div className="excel-currency" aria-label="ფასის ვალუტა"><button className={currency==="GEL"?"active":""} onClick={()=>setCurrency("GEL")}>₾</button><button className={currency==="USD"?"active":""} onClick={()=>setCurrency("USD")}>$</button></div><button onClick={addRow}>＋ ახალი ჩანაწერი</button><button className="download-sheet" onClick={download}><DownloadIcon/> ჩამოტვირთვა</button><button className="excel-icon-button close" onClick={()=>setOpen(false)} aria-label="დახურვა">×</button></div></header><div className="sheet-formula-bar"><span>JIBU</span><b>fx</b><small>VIP ბროკერის ქონების პირადი ბაზა · 1 USD = 2.6125 GEL</small></div><div className="excel-scroll"><table><thead><tr><th>#</th><th>გარიგება</th><th>ობიექტი</th><th>მდებარეობა</th><th>კვადრატულობა</th><th>სართული</th><th>ფასი ({currency})</th><th>საკონტაქტო ნომერი</th><th>ბროკერის წილი</th><th>შენიშვნა</th><th/></tr></thead><tbody>{rows.map((r,n)=><tr key={r.id}><td>{n+1}</td><td><select className={r.deal==="ქირავდება"?"rent":"sale"} value={r.deal} onChange={e=>update(r.id,"deal",e.target.value)}><option>იყიდება</option><option>ქირავდება</option></select></td>{(["title","location","area","floor","price","phone","share","note"] as (keyof Row)[]).map(k=><td key={k}><input value={k==="price"?convertedPrice(String(r[k])):String(r[k])} readOnly={k==="price"&&currency==="USD"} placeholder={k==="floor"?"მაგ: 3/9":k==="share"?"შეავსეთ":k==="note"?"აგენტის შენიშვნა":""} onChange={e=>update(r.id,k,e.target.value)}/></td>)}<td><button onClick={()=>setRows(v=>v.filter(x=>x.id!==r.id))} aria-label="ხაზის წაშლა">×</button></td></tr>)}</tbody></table></div></section>}</>
}
