"use client";
import {useEffect,useRef,useState} from "react";
import * as maplibregl from "maplibre-gl";
import {osmStyle} from "../../osm-style";
import {cityPoint} from "./georgia-cities";
type Suggestion={label:string;longitude:number;latitude:number};
export default function ListingLocationPicker({city,street,longitude,latitude,onStreetChange,onChange}:{city:string;street:string;longitude:number;latitude:number;onStreetChange:(street:string)=>void;onChange:(longitude:number,latitude:number)=>void}){
 const host=useRef<HTMLDivElement>(null),mapRef=useRef<maplibregl.Map|null>(null),markerRef=useRef<maplibregl.Marker|null>(null),suggestionCache=useRef(new Map<string,Suggestion[]>()),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[message,setMessage]=useState("ქუჩის არჩევის შემდეგ გადაამოწმე პინი");
useEffect(()=>{if(!host.current||mapRef.current)return;const probe=document.createElement("canvas");const gl=probe.getContext("webgl2");if(!gl){setMessage("რუკა ამ ბრაუზერში ვერ ჩაიტვირთა. მისამართის შეყვანა კვლავ შეგიძლია.");return;}gl.getExtension("WEBGL_lose_context")?.loseContext();const map=new maplibregl.Map({container:host.current,style:osmStyle,center:[longitude,latitude],zoom:14,attributionControl:false});mapRef.current=map;map.addControl(new maplibregl.NavigationControl({showCompass:false}),"top-right");map.addControl(new maplibregl.AttributionControl({compact:true}),"bottom-right");const pin=document.createElement("div");pin.className="jibu-drag-pin";pin.innerHTML="<span></span>";const marker=new maplibregl.Marker({element:pin,draggable:true,anchor:"bottom"}).setLngLat([longitude,latitude]);map.once("load",()=>marker.addTo(map));markerRef.current=marker;marker.on("dragend",()=>{const p=marker.getLngLat();onChange(p.lng,p.lat);setMessage("ზუსტი წერტილი ხელით მონიშნულია")});map.on("click",e=>{marker.setLngLat(e.lngLat);onChange(e.lngLat.lng,e.lngLat.lat);setMessage("ზუსტი წერტილი ხელით მონიშნულია")});return()=>{map.remove();mapRef.current=null}},[]);
 useEffect(()=>{const p=cityPoint(city);mapRef.current?.flyTo({center:[p[1],p[2]],zoom:12.5,essential:true});if(!street){markerRef.current?.setLngLat([p[1],p[2]]);onChange(p[1],p[2])}},[city]);
 const load=async(query:string,signal?:AbortSignal)=>{const key=`${city}:${query.trim().toLocaleLowerCase("ka")}`,cached=suggestionCache.current.get(key);if(cached)return cached;const p=cityPoint(city),res=await fetch(`/api/geocode?q=${encodeURIComponent(query)}&city=${encodeURIComponent(city)}&lng=${p[1]}&lat=${p[2]}`,{signal}),data=await res.json(),rows=(data.results||[]) as Suggestion[];suggestionCache.current.set(key,rows);return rows};
 useEffect(()=>{if(street.trim().length<2){setSuggestions([]);setOpen(false);return}const c=new AbortController(),timer=setTimeout(async()=>{setLoading(true);try{const rows=await load(street,c.signal);setSuggestions(rows);setOpen(rows.length>0);if(!rows.length)setMessage("ვერ მოიძებნა — სცადე ქუჩის სრული სახელი")}catch(e){if((e as Error).name!=="AbortError")setMessage("ძიება დროებით ვერ შესრულდა")}finally{setLoading(false)}},120);return()=>{clearTimeout(timer);c.abort()}},[street,city]);
 const choose=(s:Suggestion)=>{onStreetChange(s.label);onChange(s.longitude,s.latitude);markerRef.current?.setLngLat([s.longitude,s.latitude]);mapRef.current?.flyTo({center:[s.longitude,s.latitude],zoom:17,essential:true});setOpen(false);setMessage("მისამართი არჩეულია — მიუთითე ნომერი ან გადაასწორე პინი")};
 const enter=async(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key!=="Enter")return;e.preventDefault();e.stopPropagation();if(suggestions[0])return choose(suggestions[0]);setLoading(true);try{const rows=await load(street);setSuggestions(rows);if(rows[0])choose(rows[0]);else setMessage("მისამართი ვერ მოიძებნა — პინი ხელით მონიშნე")}finally{setLoading(false)}};
 return <div className="address-map-control"><label className="street-autocomplete"><span>ქუჩა, უბანი ან ადგილი</span><div><input required value={street} onChange={e=>onStreetChange(e.target.value)} onFocus={()=>suggestions.length&&setOpen(true)} onKeyDown={enter} placeholder="მაგ: ვაკე, აბაშიძის ქუჩა" autoComplete="off"/>{loading&&<i>•••</i>}</div>{open&&suggestions.length>0&&<section>{suggestions.map((s,i)=><button type="button" key={`${s.longitude}-${s.latitude}-${i}`} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(s)}><b>{s.label}</b><small>{city}, საქართველო</small></button>)}</section>}</label><label className="house-number"><span>ნომერი</span><input placeholder="მაგ: 24 ან 24ბ" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();e.currentTarget.blur()}}} onBlur={e=>{if(e.target.value&&!street.includes(e.target.value))onStreetChange(`${street}, ${e.target.value}`)}}/></label><div className="live-location-picker"><div ref={host} className="listing-live-map"/><footer><div><b>ზუსტი მდებარეობა</b><small>{message}</small><em>{latitude.toFixed(5)}, {longitude.toFixed(5)}</em></div><span>პინს შეგიძლია ხელი მოკიდო და გადაადგილო</span></footer></div></div>
}
